const donors = [
  { name: 'Kul Gouli (Raja)', commitment: 15111, donated: 15111, remarks: 'Fully Donated' },
  { name: 'Sabitra Siwakoti/ Dr. Hari Dahal', commitment: 11111, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Rajendra Karki/Gaumati Thapa', commitment: 5555, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Indira Simkhada/Diwakar Pande', commitment: 11111, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Gokul Sapkota', commitment: 5000, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Dr. Yam Giri/Paru Thapa', commitment: 11111, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Bikash Mainali', commitment: 5100, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Ram K Rai/Pabitra Adhikari', commitment: 3111, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Ravi Khadka/Ashmita Kadaria', commitment: 3111, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Sujan Regmi', commitment: 3111, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Gyanu Chand', commitment: 5001, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Durgesh Jung Karki / Neelima Karki', commitment: 11151, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Kedar kattel/ Tanka Anu Phuyal', commitment: 5555, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Devaki Sangraula/Family', commitment: 5555, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Khemanta K. Sunghk', commitment: 1151, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Raghu Neupane/Susmita Pandit', commitment: 5101, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Tej B Shahi/ Shanu Shah', commitment: 5051, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Bhubhan Shrestha / Shova Pokhrel', commitment: 5001, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Samba Lamichhane', commitment: 5100, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Ashok Karki', commitment: 5001, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Dan Singh Bista', commitment: 5001, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Govind KC/ Tej K KC', commitment: 11111, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Suraj Pokhrel/ Nirjala Pokhrel', commitment: 5555, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Bibek Goutam/ Sharita Chaulagain', commitment: 5001, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Narendra Subedi/ Santoshi Subedi', commitment: 3111, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Birendra Deuba/ Bimala Dangi', commitment: 5100, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Anonymous Life Member (HD)', commitment: 2100, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Anonymous  Member', commitment: 1110, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Anonymous  Member', commitment: 3000, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Anonymous Life Member', commitment: 5001, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Amit Singh ', commitment: 5000, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Resham Chand Thakuri ', commitment: 11111, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Tak B Ruwali ', commitment: 5001, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Dandapani Lamichhane ', commitment: 2000, donated: 0, remarks: 'No Donation Yet' },
  { name: 'Tek Man Gurung', commitment: 5000, donated: 0, remarks: 'No Donation Yet' },
];

export default donors;
